language: generic 
sudo: required
services:
  - docker

defore_install:
  - docekr build -t jasonliuhe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jasonliuhe/docker-react npm run test